version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - /Users/andrade.sampaio/Documents/Docker/Postgress/data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
          - production-network
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testdb
  # APP*****************************************
  app:
    build:
        dockerfile: /Users/andrade.sampaio/IdeaProjects/demo/Dockerfile
        context: /Users/andrade.sampaio/IdeaProjects/demo/
    image: springboot
    container_name: apiRest
    networks:
      - production-network
    ports:
      - "8080:8080"
    depends_on:
      - postgres
networks:
  production-network:
    driver: bridge